<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuz0Nsn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuz0Nsn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXuz0Nsn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXuz0Nsn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXuz0Nsn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xuz0Nsn',
    'container.build_id' => '1e2df5fc',
    'container.build_time' => 1594639247,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuz0Nsn');
