<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8OhJNxa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8OhJNxa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8OhJNxa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8OhJNxa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8OhJNxa\App_KernelDevDebugContainer([
    'container.build_hash' => '8OhJNxa',
    'container.build_id' => 'acc3cdcd',
    'container.build_time' => 1594295251,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8OhJNxa');
